version: "3.9"
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./log:/var/log/nginx
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
